<?php
/**
* @OA\Get(
*      path="/api/teachers/{id}",
*      operationId="id",
*      tags={"Teachers"},
*      summary="取得老師",
*      description="取得老師",
*      @OA\Parameter(
*          name="id",
*          description="id",
*          required=true,
*          in="path",
*          @OA\Schema(
*              type="integer"
*          )
*      ),
*      @OA\Response(
*          response=200,
*          description="請求成功"
*       ),
*      @OA\Response(
*          response=404,
*          description="資源不存在"
*       )
* )
* Show article content


* @OA\Post(
*      path="/api/teachers",
*      operationId="teacherPost",
*      tags={"Teachers"},
*      summary="新增老師",
*      description="新增老師",
*      @OA\Parameter(
*          name="teacherName",
*          required=true,
*          in="query",
*          @OA\Schema(
*              type="string"
*          )
*      ),
*      @OA\Response(
*          response=201,
*          description="資源成功建立"
*       ),
*      @OA\Response(
*          response=400,
*          description="請求格式錯誤"
*       )
* )
* Create a teacher

* @OA\Put(
*      path="/api/teachers/{id}",
*      operationId="teacherChange",
*      tags={"Teachers"},
*      summary="更新老師資訊",
*      description="更新老師資訊",
*      @OA\Parameter(
*          name="id",
*          description="id",
*          required=false,
*          in="query",
*          @OA\Schema(
*              type="integer"
*          )
*      ),
*      @OA\Parameter(
*          name="teacherName",
*          description="老師名稱",
*          required=false,
*          in="query",
*          @OA\Schema(
*              type="string"
*          )
*      ),
*      @OA\Response(
*          response=200,
*          description="請求成功"
*       ),
*      @OA\Response(
*          response=404,
*          description="資源不存在"
*       )
* )

* @OA\Delete(
*      path="/api/teachers/{id}",
*      operationId="TeacherDelete",
*      tags={"Teachers"},
*      summary="刪除老師",
*      description="刪除老師",
*      @OA\Parameter(
*          name="id",
*          description="Teacher id",
*          required=true,
*          in="path",
*          @OA\Schema(
*              type="integer"
*          )
*      ),
*      @OA\Response(
*          response=201,
*          description="請求成功"
*       ),
*      @OA\Response(
*          response=404,
*          description="資源不存在"
*       )
* )
* Delete article content
*
* @OA\Get(
*      path="/api/courses/{courseId}",
*      operationId="courses",
*      tags={"Courses"},
*      summary="取得課程",
*      description="取得課程",
*      @OA\Parameter(
*          name="courseId",
*          description="courseId",
*          required=true,
*          in="path",
*          @OA\Schema(
*              type="integer"
*          )
*      ),
*      @OA\Response(
*          response=200,
*          description="請求成功"
*       ),
*      @OA\Response(
*          response=404,
*          description="找不到對應課程"
*       )
* )
* @OA\Post(
*      path="/api/courses",
*      operationId="coursesPost",
*      tags={"Courses"},
*      summary="新增課程",
*      description="新增課程",
*      @OA\Parameter(
*          name="name",
*          description="課程名稱",
*          required=true,
*          in="query",
*          @OA\Schema(
*              type="string"
*          )
*      ),
*      @OA\Parameter(
*          name="description",
*          description="description",
*          required=false,
*          in="query",
*          @OA\Schema(
*              type="string"
*          )
*      ),
*      @OA\Parameter(
*          name="outline",
*          description="description",
*          required=false,
*          in="query",
*          @OA\Schema(
*              type="string"
*          )
*      ),
*      @OA\Response(
*          response=200,
*          description="資源成功建立"
*       ),
*      @OA\Response(
*          response=422,
*          description="驗證錯誤"
*       )
* )
*
* @OA\Patch(
*      path="/api/courses/{courseId}",
*      operationId="coursesPatch",
*      tags={"Courses"},
*      summary="更新課程",
*      description="更新課程",
*      @OA\Parameter(
*          name="courseId",
*          description="courseId",
*          required=true,
*          in="path",
*          @OA\Schema(
*              type="integer"
*          )
*      ),
*      @OA\Parameter(
*          name="name",
*          description="課程名稱",
*          required=false,
*          in="query",
*          @OA\Schema(
*              type="string"
*          )
*      ),
*      @OA\Parameter(
*          name="description",
*          description="description",
*          required=false,
*          in="query",
*          @OA\Schema(
*              type="string"
*          )
*      ),
*      @OA\Parameter(
*          name="outline",
*          description="description",
*          required=false,
*          in="query",
*          @OA\Schema(
*              type="string"
*          )
*      ),
*      @OA\Response(
*          response=200,
*          description="請求成功"
*       ),
*      @OA\Response(
*          response=404,
*          description="資源不存在"
*       )
* )
* @OA\Delete(
*      path="/api/courses/{courseId}",
*      operationId="coursesDelete",
*      tags={"Courses"},
*      summary="刪除課程",
*      description="刪除課程",
*      @OA\Parameter(
*          name="courseId",
*          description="courseId",
*          required=true,
*          in="path",
*          @OA\Schema(
*              type="integer"
*          )
*      ),
*      @OA\Response(
*          response=200,
*          description="刪除成功"
*       ),
*      @OA\Response(
*          response=404,
*          description="課程找不到"
*       )
* )
*
*/